
nome: CI


em: [push, workflow_dispatch]


empregos:

  construir:


    executado: windows-latest


    degraus:

    - nome: Baixar

      execute: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - nome: Extrair

      execute: Expand-Archive ngrok.zip

    - nome: Autenticação

      execute: .\ngrok\ngrok.exe token de autenticação $Env:NGROK_AUTH_TOKEN

      ambiente:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - nome: Ativar TS

      execute: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - execute: Enable-NetFirewallRule -DisplayGroup "Área de Trabalho Remota"

    - execute: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - nome: Criar túnel

      execute: .\ngrok\ngrok.exe tcp 3389
